### ISSUE TITLE
Initialize ReadTheDocs Project

### ISSUE THREAD

**Issue by DominicParent** [ryanmwhitephd/artemis#1]
1) Need to claim the namespace for the readthedocs projects.
2) Create rst file in the docs folder.
3) Build and post to readthedocs site.

**Comment by ryanmwhitephd** [comment]
Available in master. Any work on my side to publish on documentation with github actions?

**Comment by DominicParent** [comment]
No, readthedocs has webhooks if you log in with your github account. You gave me sufficient permissions to allow them to pull the content and build the documentation. I just need to troubleshoot the configuration.

**Comment by DominicParent** [comment]
The pyartemis project has been deployed on readthedocs. There's some more work to be done in terms of setting up webhooks, but we should first set up a proper deployment strategy before automating publishing documentation. I see no reason to be wasteful of the readthedocs resources.
