### ISSUE TITLE
Getting started documentation

### ISSUE THREAD

**Issue by ryanmwhitephd** [ryanmwhitephd/artemis#6]
@russellgill or @DominicParent, since you too are most familiar now can either of you create a Getting Started document in `artemis/docs/getting-started.rst`. Minimum is

- Create a conda environment for developing
- Get the required dependencies
- Add / build fwfr from Kira's github version
- Run the test suite
- Run one of the examples

**Comment by DominicParent** [comment]
I'll take a crack at it, I'm currently working on getting the whole thing working properly on readthedocs.

**Comment by DominicParent** [comment]
The feature-6 branch currently contains information from the README, converted to the rst format instead of md.

**Comment by ryanmwhitephd** [comment]
@DominicParent 
Merge these changes into master?
How to get sphinx setup to test documentation locally?

**Comment by DominicParent** [comment]
@ryanmwhitephd There's still a change I want to make to this basic version of the documentation before merging to master.

I'll document the technical information of how to build/configure our environments in the Github Wiki.

**Comment by DominicParent** [comment]
I updated branch-6 with the small modification I wanted to make before pulling and merging. The branch can be merged now, the modifications fulfill the initial requirements of this issue.

**Comment by ryanmwhitephd** [comment]
Thanks, I've merged the branch.
